// Code generated by MockGen. DO NOT EDIT.
// Source: ../../slack/slack.go

// Package slack is a generated GoMock package.
package slack

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	slack "github.com/slack-go/slack"
)

// MockSlackClientWrapper is a mock of SlackClientWrapper interface.
type MockSlackClientWrapper struct {
	ctrl     *gomock.Controller
	recorder *MockSlackClientWrapperMockRecorder
}

// MockSlackClientWrapperMockRecorder is the mock recorder for MockSlackClientWrapper.
type MockSlackClientWrapperMockRecorder struct {
	mock *MockSlackClientWrapper
}

// NewMockSlackClientWrapper creates a new mock instance.
func NewMockSlackClientWrapper(ctrl *gomock.Controller) *MockSlackClientWrapper {
	mock := &MockSlackClientWrapper{ctrl: ctrl}
	mock.recorder = &MockSlackClientWrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlackClientWrapper) EXPECT() *MockSlackClientWrapperMockRecorder {
	return m.recorder
}

// getConversationReplies mocks base method.
func (m *MockSlackClientWrapper) getConversationReplies(arg0 *slack.GetConversationRepliesParameters) ([]slack.Message, bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getConversationReplies", arg0)
	ret0, _ := ret[0].([]slack.Message)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// getConversationReplies indicates an expected call of getConversationReplies.
func (mr *MockSlackClientWrapperMockRecorder) getConversationReplies(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getConversationReplies", reflect.TypeOf((*MockSlackClientWrapper)(nil).getConversationReplies), arg0)
}

// getConversations mocks base method.
func (m *MockSlackClientWrapper) getConversations(arg0 *slack.GetConversationsParameters) ([]slack.Channel, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getConversations", arg0)
	ret0, _ := ret[0].([]slack.Channel)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// getConversations indicates an expected call of getConversations.
func (mr *MockSlackClientWrapperMockRecorder) getConversations(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getConversations", reflect.TypeOf((*MockSlackClientWrapper)(nil).getConversations), arg0)
}
