# Provide a custom message
message: ""

# Remember to set service.type=ClusterIP if you are using an ingress
ingress:
  configured: false
  rewritePath: true
  pathPrefix: ""

service:
  type: LoadBalancer
  port: 80

slackConfig:
  signingSecret: ""
  botToken: ""

jiraConfig:
  username: ""
  password: ""
  url: ""

deployment:
  replicaCount: 2
  container:
    image:
      repository: "ghcr.io/jshaw86/slack-jira-integration/slack-jira"
      tag: "latest" # uses chart appVersion if not provided
      pullPolicy: IfNotPresent
    port: 8000

  # Currently only linux images on amd64 architecture are supported - support for arm64 and windows/amd64 coming ...
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64

  resources: {}

  tolerations: []

  affinity: {}

