// Code generated by MockGen. DO NOT EDIT.
// Source: ../../jira/jira.go

// Package jira is a generated GoMock package.
package jira

import (
	reflect "reflect"

	jira "github.com/andygrunwald/go-jira"
	gomock "github.com/golang/mock/gomock"
)

// MockJiraer is a mock of Jiraer interface.
type MockJiraer struct {
	ctrl     *gomock.Controller
	recorder *MockJiraerMockRecorder
}

// MockJiraerMockRecorder is the mock recorder for MockJiraer.
type MockJiraerMockRecorder struct {
	mock *MockJiraer
}

// NewMockJiraer creates a new mock instance.
func NewMockJiraer(ctrl *gomock.Controller) *MockJiraer {
	mock := &MockJiraer{ctrl: ctrl}
	mock.recorder = &MockJiraerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJiraer) EXPECT() *MockJiraerMockRecorder {
	return m.recorder
}

// createIssue mocks base method.
func (m *MockJiraer) createIssue(arg0 *jira.Issue) (*jira.Issue, *jira.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "createIssue", arg0)
	ret0, _ := ret[0].(*jira.Issue)
	ret1, _ := ret[1].(*jira.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// createIssue indicates an expected call of createIssue.
func (mr *MockJiraerMockRecorder) createIssue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "createIssue", reflect.TypeOf((*MockJiraer)(nil).createIssue), arg0)
}

// getSelf mocks base method.
func (m *MockJiraer) getSelf() (*jira.User, *jira.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getSelf")
	ret0, _ := ret[0].(*jira.User)
	ret1, _ := ret[1].(*jira.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// getSelf indicates an expected call of getSelf.
func (mr *MockJiraerMockRecorder) getSelf() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getSelf", reflect.TypeOf((*MockJiraer)(nil).getSelf))
}
