---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack
data:
  SLACK_SIGNING_SECRET: {{ .Values.slackConfig.signingSecret | b64enc }} 
  SLACK_BOT_TOKEN: {{ .Values.slackConfig.botToken | b64enc }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jira
data:
  USER_NAME: {{ .Values.jiraConfig.username | b64enc }} 
  PASSWORD: {{ .Values.jiraConfig.password | b64enc }}
